---
# Docker Compose creates multiple containers on a single machine.
# run `docker compose up` to create and run/link the containers
services:
  web:
    container_name: seed_web
    image: eawebapps.azurecr.io/seedplatform/seed:latest
    ports:
      - "8080:80"
    volumes:
      - seed_media:/seed/media
  web-celery:
    container_name: seed_celery
    image: eawebapps.azurecr.io/seedplatform/seed:latest
    command: /seed/docker/start_celery_docker.sh
    depends_on:
      - web
    volumes:
      - seed_media:/seed/media
volumes:
  seed_media:
    external: true
